### PR TITLE
Add finish touches to leaderboard app

### PR DESCRIPTION
**Pull request by bimbolabuari**
# Leaderboard Microverse Project  🚀 

 > This PR adds a project about sending and receiving data from an API that showcases the knowledge and use of JSON, Webpack Configuration, Javascript, import and export modules, async and await, fetch API, making JavaScript code asynchronous.

## Built With 😉

- Semantic HTML & CSS
- Linters (Stylelint, Web hint, Lighthouse)

## Live Preview 👍 

[Live Preview Link](https://deploy-preview-3--bimbola-mv-leaderboard.netlify.app/)

### CODE REVIEW

**Review by mikenath223 — CHANGES_REQUESTED** [review]
Hello @bimbolabuari,

You've done pretty well so far!
But for a few issues, you are almost done with this. Hang in there!


## Required Changes ♻️
_Please check the comments under the review._
- [ ] Kindly update the readme with the correct deploy link, as the present link there throws a 404 error.

Happy coding, Cheers! 🚀🚀

Do feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, whether it is valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by bimbolabuari** [comment]
Hello @mikenath223, I used the correct deploy link on my readme generated by Github, Kindly check the screenshot below:

Screenshot (530)

I will appreciate your feedback on what to do. Thanks 🙂

**Comment by mikenath223** [comment]
Hello, perhaps consider using the netlify deploy link in the PR description.

**Review by MahmoudBakr23 — APPROVED** [review]
Hi @bimbolabuari 😃, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit:
Congratulations! 🎉  

**Optional**
- Kindly make sure to put the link you attached in the PR into the README file instead of this one.

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by bimbolabuari** [comment]
@mikenath223, @MahmoudBakr23,
I already made the changes and added my Netlify deployed link to my readme, thanks 👍 
@MahmoudBakr23,
Thanks for approving the project 🎉

**Pull request merged**
